// Seed data used to populate the board the first time the database is created.
const hoursAgo = (h) => Date.now() - h * 60 * 60 * 1000;

export const SEED_JOBS = [
  { id: "seed-1", title: "Senior Backend Engineer", company: "Harborlight Systems", location: "Remote (US)", type: "Full-time", salary: "$150k–$190k", salaryMin: 150, salaryMax: 190, shift: "Flexible", vacancies: 3, tags: ["backend", "go", "distributed-systems"], apply: "careers@harborlight.example", description: "Own the payments ledger service. Go, Postgres, and a healthy respect for idempotency keys.", postedAt: hoursAgo(1), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-2", title: "Product Designer", company: "Fernweh Travel Co.", location: "Lisbon, PT (Hybrid)", type: "Full-time", salary: "€65k–€80k", salaryMin: 65, salaryMax: 80, shift: "Day", vacancies: 1, tags: ["design", "figma", "b2c"], apply: "https://fernweh.example/careers/product-designer", description: "Design the booking flow used by ~2M travelers a year.", postedAt: hoursAgo(5), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-3", title: "Data Analyst (Contract, 3mo)", company: "Northline Freight", location: "Remote (EU)", type: "Contract", salary: "$60/hr", salaryMin: null, salaryMax: null, shift: "Flexible", vacancies: 2, tags: ["sql", "analytics", "logistics"], apply: "jobs@northline.example", description: "Build a route-efficiency dashboard from raw telematics data.", postedAt: hoursAgo(22), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-4", title: "Support Engineer (Night Shift)", company: "Cascade Cloud", location: "Remote (Any)", type: "Part-time", salary: "$40k–$50k", salaryMin: 40, salaryMax: 50, shift: "Night", vacancies: 4, tags: ["support", "linux", "customer-facing"], apply: "https://cascadecloud.example/jobs/support-night", description: "Cover the 10pm–4am UTC window for a small infra team.", postedAt: hoursAgo(30), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-5", title: "Machine Learning Engineer", company: "Ridgeline Analytics", location: "Austin, TX (Hybrid)", type: "Full-time", salary: "$140k–$175k", salaryMin: 140, salaryMax: 175, shift: "Flexible", vacancies: 3, tags: ["ml", "python", "pytorch"], apply: "careers@ridgeline.example", description: "Build forecasting models used across the supply chain team.", postedAt: hoursAgo(3), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-6", title: "Registered Nurse", company: "BrightPath Health", location: "Chicago, IL", type: "Full-time", salary: "$75k–$95k", salaryMin: 75, salaryMax: 95, shift: "Rotating", vacancies: 10, tags: ["healthcare", "nursing", "patient-care"], apply: "hr@brightpath.example", description: "Join a 40-bed med-surg unit with a strong nurse-to-patient ratio.", postedAt: hoursAgo(6), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-7", title: "3D Environment Artist", company: "Loomcraft Studios", location: "Remote (Global)", type: "Contract", salary: "$50/hr", salaryMin: null, salaryMax: null, shift: "Flexible", vacancies: 2, tags: ["3d", "blender", "game-art"], apply: "jobs@loomcraft.example", description: "Build modular environment kits for a narrative-driven indie title.", postedAt: hoursAgo(9), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-8", title: "Store Associate", company: "Summit Retail Group", location: "Denver, CO", type: "Part-time", salary: "$18/hr", salaryMin: null, salaryMax: null, shift: "Day", vacancies: 15, tags: ["retail", "customer-service"], apply: "https://summitretail.example/careers", description: "Help customers on the floor and keep the store looking sharp.", postedAt: hoursAgo(12), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-9", title: "Warehouse Supervisor", company: "Vantage Logistics", location: "Newark, NJ", type: "Full-time", salary: "$58k–$68k", salaryMin: 58, salaryMax: 68, shift: "Night", vacancies: 4, tags: ["logistics", "warehouse", "ops"], apply: "careers@vantagelogistics.example", description: "Run the overnight shift for a 200k sq ft distribution center.", postedAt: hoursAgo(14), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-10", title: "Paralegal", company: "Clearwater Legal", location: "Boston, MA (Hybrid)", type: "Full-time", salary: "$55k–$70k", salaryMin: 55, salaryMax: 70, shift: "Day", vacancies: 2, tags: ["legal", "paralegal"], apply: "hiring@clearwaterlegal.example", description: "Support a small commercial litigation team.", postedAt: hoursAgo(16), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-11", title: "Security Analyst", company: "Nimbus Cloud Security", location: "Remote (US)", type: "Full-time", salary: "$95k–$120k", salaryMin: 95, salaryMax: 120, shift: "Rotating", vacancies: 3, tags: ["security", "siem", "cloud"], apply: "https://nimbuscloud.example/careers/security-analyst", description: "Triage alerts across a SIEM covering 400+ cloud accounts.", postedAt: hoursAgo(18), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-12", title: "Agronomy Field Technician", company: "Greenfield Agritech", location: "Fresno, CA", type: "Full-time", salary: "$48k–$56k", salaryMin: 48, salaryMax: 56, shift: "Day", vacancies: 6, tags: ["agriculture", "fieldwork"], apply: "careers@greenfieldagritech.example", description: "Collect soil and crop-health samples across partner farms.", postedAt: hoursAgo(20), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-13", title: "Gameplay Programmer", company: "PixelForge Games", location: "Remote (EU)", type: "Full-time", salary: "€55k–€75k", salaryMin: 55, salaryMax: 75, shift: "Flexible", vacancies: 2, tags: ["gamedev", "c++", "unity"], apply: "jobs@pixelforge.example", description: "Ship combat and traversal systems for a co-op action title.", postedAt: hoursAgo(26), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-14", title: "CNC Machinist", company: "Northgate Manufacturing", location: "Detroit, MI", type: "Full-time", salary: "$52k–$64k", salaryMin: 52, salaryMax: 64, shift: "Night", vacancies: 8, tags: ["manufacturing", "cnc"], apply: "hr@northgatemfg.example", description: "Run and maintain 5-axis CNC mills producing precision parts.", postedAt: hoursAgo(28), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-15", title: "Front Desk Associate", company: "Sable & Finch Hospitality", location: "Miami, FL", type: "Part-time", salary: "$16/hr", salaryMin: null, salaryMax: null, shift: "Rotating", vacancies: 5, tags: ["hospitality", "front-desk"], apply: "careers@sableandfinch.example", description: "Be the first face guests see at a 120-room boutique hotel.", postedAt: hoursAgo(32), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-16", title: "Junior Accountant", company: "Ledgerline Accounting", location: "Remote (US)", type: "Full-time", salary: "$50k–$62k", salaryMin: 50, salaryMax: 62, shift: "Day", vacancies: 3, tags: ["accounting", "finance"], apply: "jobs@ledgerline.example", description: "Handle monthly close support for a portfolio of small-business clients.", postedAt: hoursAgo(36), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-17", title: "Mechanical Design Engineer", company: "OrbitalWorks Aerospace", location: "Huntsville, AL", type: "Full-time", salary: "$85k–$105k", salaryMin: 85, salaryMax: 105, shift: "Day", vacancies: 2, tags: ["aerospace", "cad", "mechanical"], apply: "careers@orbitalworks.example", description: "Design brackets and fixtures for small-satellite payload integration.", postedAt: hoursAgo(40), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-18", title: "Line Cook", company: "BrewHouse Collective", location: "Portland, OR", type: "Part-time", salary: "$19/hr", salaryMin: null, salaryMax: null, shift: "Night", vacancies: 6, tags: ["culinary", "kitchen"], apply: "kitchen@brewhousecollective.example", description: "Work the line at a busy gastropub kitchen.", postedAt: hoursAgo(44), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-19", title: "Curriculum Developer", company: "Trellis Education", location: "Remote (Any)", type: "Contract", salary: "$45/hr", salaryMin: null, salaryMax: null, shift: "Flexible", vacancies: 2, tags: ["education", "instructional-design"], apply: "jobs@trelliseducation.example", description: "Write and revise middle-school math modules for an adaptive learning platform.", postedAt: hoursAgo(48), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-20", title: "Claims Adjuster", company: "Ironclad Insurance", location: "Columbus, OH (Hybrid)", type: "Full-time", salary: "$54k–$66k", salaryMin: 54, salaryMax: 66, shift: "Day", vacancies: 5, tags: ["insurance", "claims"], apply: "careers@ironcladinsurance.example", description: "Review and process auto claims end-to-end.", postedAt: hoursAgo(52), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-21", title: "Automotive Technician", company: "DriftLine Auto", location: "San Antonio, TX", type: "Full-time", salary: "$22/hr", salaryMin: null, salaryMax: null, shift: "Rotating", vacancies: 7, tags: ["automotive", "repair"], apply: "hire@driftlineauto.example", description: "Diagnose and repair a mix of domestic and import vehicles.", postedAt: hoursAgo(56), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-22", title: "Program Coordinator", company: "Beacon Nonprofit Alliance", location: "Seattle, WA", type: "Full-time", salary: "$48k–$58k", salaryMin: 48, salaryMax: 58, shift: "Day", vacancies: 2, tags: ["nonprofit", "program-management"], apply: "jobs@beaconalliance.example", description: "Coordinate volunteer scheduling and grant reporting.", postedAt: hoursAgo(60), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-23", title: "Site Safety Officer", company: "Quarrystone Construction", location: "Salt Lake City, UT", type: "Full-time", salary: "$60k–$72k", salaryMin: 60, salaryMax: 72, shift: "Day", vacancies: 3, tags: ["construction", "safety"], apply: "careers@quarrystone.example", description: "Run daily safety walkthroughs across two active commercial sites.", postedAt: hoursAgo(64), postedById: "seed-employer", postedByName: "Demo Employer" },
  { id: "seed-24", title: "Podcast Audio Editor", company: "EchoWave Media", location: "Remote (Global)", type: "Contract", salary: "$35/hr", salaryMin: null, salaryMax: null, shift: "Flexible", vacancies: 4, tags: ["audio", "editing", "media"], apply: "jobs@echowavemedia.example", description: "Edit and master weekly interview episodes across three shows.", postedAt: hoursAgo(68), postedById: "seed-employer", postedByName: "Demo Employer" },
];
